### ISSUE TITLE
Colorize in single pass

### ISSUE THREAD

**Issue by prgoodwin** [nischalshrestha/CogulatorPlus#11]
weird things happen in multipass coloring.  THis requires globalizing the state table and doing some parsing in ColorSyntax.

**Comment by nischalshrestha** [comment]
This might be because of the way we are currently colorizing, I noticed the solarizeAll() seems to be messing up highlighting sometimes. I can take a stab at this today, which will potentially fix the coloring issues I was seeing last night with making colon optional.
