### ISSUE TITLE
Bug on parsing a colon; make it optional

### ISSUE THREAD

**Issue by nischalshrestha** [nischalshrestha/CogulatorPlus#18]

**Comment by prgoodwin** [comment]
I uploaded a folder called Models that has all of my parsing syntax tests.  Can we make it a point to keep that file updated with any parsing success/failures?

**Comment by nischalshrestha** [comment]
Sure I can add those cases

**Comment by nischalshrestha** [comment]
Made it optional colon for both goto and the goal in goto so any of these is valid:

goto: goal: some goal
goto: goal some goal
goto goal: some goal
goto goal some goal
