### ISSUE TITLE
If the goto refers to a non-unique goal name, fetch the first or last?

### ISSUE THREAD

**Issue by nischalshrestha** [nischalshrestha/CogulatorPlus#34]
Since modelers could potentially have goals with the same name but different actions, fetching the first goal found down the model is probably fine. Could add a hint saying, "Try giving goals a unique name, otherwise the first will be picked with goto"

**Comment by nischalshrestha** [comment]
Since goalTable is a Dict, the current implementation will fetch the last goal since if it will override the first one. Is this reasonable?

**Comment by prgoodwin** [comment]
This is probably fine.  It's bad coding practice, so I think it's safe to do whatever.  How hard would it be to have it error out if it finds a goto line with multiple jump possibilities?

**Comment by nischalshrestha** [comment]
We would need to change the DS for the value to be an Array instead of a single value. Not too hard.

**Comment by nischalshrestha** [comment]
We have gone with choosing the first one, and possibly adding a hint in the future about it.
