### ISSUE TITLE
Checking equality of one variable, makes another evaluate incorrectly

### ISSUE THREAD

**Issue by prgoodwin** [nischalshrestha/CogulatorPlus#39]
Something is wrong with the if-statement logic.  Even without gotos involved.  Example in branch test:

CreateState target1 isfriendly 
CreateState target2 isfriendly 
CreateState target3 isfriendly 

SetState target1 isEnemy 
SetState target2 isEnemy 
SetState target3 isEnemy 

...*stuff happens here

. If target1 isEnemy
. initiate hand-movement
. hands to target (301 ms)
. touch target
. SetState target1 isfriendly
. . If target1 isfriendly
. . . If target2 isfriendly
. . . . If target3 isfriendly *<--!-- When commented the target2 if-statement evaluates true and it is touched.  When uncommented, target2 if-statement evaluates false and is not touched.
*. . . . . GoTo Goal: endOfLevel
. . . . EndIf
. . . EndIf
. . EndIf
. EndIf  
*
*
Goal: visit target2
.attend  target2
.initiate eye-movement
.saccade to target2 
.Perceptual_processor perceive target2 (100 ms)
.verify target2 (50 ms)
. If target2 isEnemy
. initiate hand-movement
. hands to target (301 ms)
. touch target
. EndIf

**Comment by nischalshrestha** [comment]
Yep. I was wrestling with this last night and haven't fixed it or figured out the problem. It's odd but you can create a new model and do some tests with multiple ifs and see what happens.

**Comment by nischalshrestha** [comment]
See CogulatorPlus/models/IfDiabolical.goms.

**Comment by nischalshrestha** [comment]
Did you remember to comment out corresponding EndIf as well? Remember that EndIfs are required now.

**Comment by prgoodwin** [comment]
yeah, that's not the problem.

On Fri, Jul 21, 2017 at 12:05 PM, Nischal Shrestha <notifications@github.com

**Comment by nischalshrestha** [comment]
Okay it seems to be invalidating incorrectly

**Comment by nischalshrestha** [comment]
Okay I found the issue, I'll push the fix soon. The problem was that I was checking against the parentIfObject to be null instead of checking against the parentIfIndex. For some reason parentIfObject was not null by default.
