### ISSUE TITLE
CogulatorPlus/classes/CogulatorPlusProcessor.as still being used?

### ISSUE THREAD

**Issue by nischalshrestha** [nischalshrestha/CogulatorPlus#4]

**Comment by nischalshrestha** [comment]
This seems like the wrapper idea, if not used let's delete it.

**Comment by prgoodwin** [comment]
This file and BranchingWrapperFunctionality both were approaches that ended up not working. Both should be good to delete. (There may still be one reference to BranchingWrapperFunctionality in Main that needs to be changed as well.)
