### ISSUE TITLE
No error for same named jump 

### ISSUE THREAD

**Issue by prgoodwin** [nischalshrestha/CogulatorPlus#44]
Pretty sure it just chooses the first one, but I'd love a hint about this.

**Comment by nischalshrestha** [comment]
Yea, it's not necessarily an error so it could be a hint. The way you add hints is different because there's no global variable like errors, so it might be tricky.

**Comment by nischalshrestha** [comment]
See the method newHints() in HintsTool class where the inter steps are examined to insert hints. What you could do is check for goals and see if you get two of the same.
