### ISSUE TITLE
Have some kind of counter variable / mechanism for loops

### ISSUE THREAD

**Issue by nischalshrestha** [nischalshrestha/CogulatorPlus#6]
This is just an idea I had, and more of an enhancement.

- Might avoid the issue of infinite loops if coerced to have a finite count
- Might be a special variable / operator to indicate variable is for counting
- With conditional variables, it would be useful for "bracketing" to look at the worst and the best performance on a model (worst of way of interacting versus best way) simulating an experiment.

**Comment by prgoodwin** [comment]
While this feature could be useful, I don't think it's right to combine it with goto statements.  I could see v2 having a "do loop" though with this functionality.

**Comment by nischalshrestha** [comment]
Yea, it doesn't have to be combined with goto, it could be like you say a separate syntax entirely for loops and "do loop" definitely sounds good. I would just like to see a way to set loops at some point in the future.

**Comment by prgoodwin** [comment]
Another thing worth thinking about with this one (and I'm not the right person to ask about this) is whether do loops are an appropriate feature in a goms model.  You delved a lot deeper into some of this stuff than I did.  Did glean have do-loops or the like?

**Comment by nischalshrestha** [comment]
No, loops seem to be implicit, see Figure 6 and the discussion [here](http://acs.ist.psu.edu/papers/stamantFR05.pdf). Also, there is no mention of a loop syntax besides Goto in the "A guide to GOMS model usability evaluation using GOMSL" reference. I assume GLEAN won't either since it is based on GOMSL. So, one solution is just to have "state goals" that set a state variable to the next one and if we go that route we don't need a new syntax; the downside being it's a bit more work and clumsy.
