### ISSUE TITLE
Making sure one goal finishes before the next one begins

### ISSUE THREAD

**Issue by prgoodwin** [nischalshrestha/CogulatorPlus#7]
Multitasking has some weird behavior.  

1. Goal: Must complete first
2. .Goal: hands 
3. ..attend  display_change
4. .Also eyes
5 .. mouseUp (150 ms)

does the same thing as 

1. Goal: Must complete first
2. .Goal: hands 
3 .. mouseUp (150 ms)
4. .Also eyes
5. ..attend  display_change

unless there is something after it.  The next goal starts when the main thread finishes instead of waiting for both.  

1. Goal: Must complete first
2. .Goal: hands 
3. ..attend  display_change
4. .Also eyes
5 .. mouseUp (150 ms)
6. Goal: must begin after both finish
7. perceptual_processor  perceive-display
8. verify display-change (50 ms)

**Comment by nischalshrestha** [comment]
I noticed that as well. Currently everything is parsed and concatenated in the timeline as it is encountered down the file, so as soon as the operators in one goal finishes, whatever operators follow will continue if they're not within an Also. We just need a check that looks for any Also's in the previous goal and look at the Also (if there are multiple in different threads) with the longest time, and begin the current goal after the end time of that Also.

**Comment by nischalshrestha** [comment]
This could probably be handled now with the way I've created Goal objects that hold information about its scope.
